version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER:?DB_USER is not set}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?DB_PASSWORD is not set}
      - POSTGRES_DB=${DB_NAME:-PROD_DB}
