version: '3'

services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=DEV_DB

  cache:
    extends:
      file: docker-compose.yml
      service: cache
    ports:
      - "6379:6379"

  broker:
    extends:
      file: docker-compose.yml
      service: broker
    ports:
      - 5672:5672
      - 15672:15672
